#!/bin/bash
# BASHWebCam, Alex Stanev <alex@stanev.org>
# A simple bash script, implementing HTTP web server and online video streaming with VLC
# https://github.com/realender/bashwebcam
# The source code is distributed under GPLv3 license

# Configuration start
# Web server port
PORT=9000
# VLC streaming port
VPORT=8080
# Video host
VHOST="http://localhost"
# Access password
PASS="changeme"
# Configuration end

VERSION="0.2"
# FIFO name
RESP=$(mktemp -u)
VKEY=$(head -c 64 /dev/urandom | sha512sum -b | head -c 128)
SALT=$(head -c 64 /dev/urandom | sha512sum -b | head -c 128)
PSALT=$(echo -n $SALT$(echo -n $PASS | sha512sum | head -c 128) | sha512sum | head -c 128)
VURL="$VHOST:$VPORT/$VKEY.ogv"
VPID=0

server_init() {
    if [[ -p $RESP ]]; then
        echo "bwc $VERSION already runs wild!"
        exit
    fi
    mkfifo $RESP
    # cleanup fifo
    trap "rm -f $RESP;kill 0" EXIT
    echo "bwc $VERSION initialized"
}

server_404() {
    cat >$RESP <<EOF
HTTP/1.0 404 Not Found
Content-Type: text/plain
Server: bashwebcam/$VERSION

404 Not Found
EOF
}

server_return() {
    cat >$RESP <<EOF
HTTP/1.0 200 OK
Cache-Control: no-cache
Content-Type: text/html
Server: bashwebcam/$VERSION
Connection: Close
Content-Length: ${#1}

$1
EOF
}

server_index() {
    server_return "$(cat <<EOF
<!DOCTYPE html>

<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>BASHWebCam</title>
    <script src="http://crypto-js.googlecode.com/svn/tags/3.1.2/build/rollups/sha512.js"></script>
    <script type="text/javascript">
        var salt="$SALT";
        var url="";
        function doCommand(comm) {
            var psalt = CryptoJS.SHA512(salt+CryptoJS.SHA512(document.getElementById("pass").value));
            var xhReq = new XMLHttpRequest();
            xhReq.open("GET", "/"+comm+"="+psalt, false);
            xhReq.send(null);
            if (xhReq.status == 200)
                return xhReq.responseText;

            return "";
        }
        function doStart() {
            url = doCommand("start");
            if (url == "") {
                alert("Bad password");
                return;
            }
            window.onbeforeunload = function() {
                doCommand("stop");
            }

            setTimeout(function() {
                var bwc = document.getElementById("bwc");
                bwc.src = url;
                bwc.play();
            }, (5000)); 
        }
        function doStop() {
            doCommand("stop");
            var bwc = document.getElementById("bwc");
            bwc.pause();
            bwc.src = "";
        }
    </script>
</head>

<body>
<h1>BASH WebCam view</h1>
<video id="bwc" type='video/ogg; codecs="theora"' preload="none" autoplay="">
Your browser does not support theora video.
</video>
<hr/>
Password: <input id="pass" type="password" />
<input type="button" onclick="doStart();" value="Start" />
<input type="button" onclick="doStop();" value="Stop" />
</body>
</html>
EOF
)"
}

stream_start() {
    if [ $VPID -eq 0 ]; then
        cvlc v4l2:// --sout="#transcode{vcodec=theo,vb=800,scale=0}:http{dst=:$VPORT/$VKEY.ogv}" &
        VPID=$!
    fi
    server_return "$VURL"
}

stream_stop() {
    if [ $VPID -ne 0 ]; then
        kill $VPID
        VPID=0
        server_return "Stopping..."
        return
    fi
    server_return "Not streaming yet"
}

# Here we start
server_init

while true ; do
    {
    REQ=`while read L && [ " " "<" "$L" ] ; do echo "$L" ; done`
    echo "[`date '+%Y-%m-%d %H:%M:%S'`] $REQ" | head -1

    URL="${REQ% HTTP/*}"

    case "$URL" in
        "GET /")
            server_index
            ;;
        "GET /start=$PSALT")
            stream_start
            ;;
        "GET /stop=$PSALT")
            stream_stop
            ;;
        *)
            server_404
            ;;
    esac
    echo "VPID=$VPID"
    } < <(nc -l $PORT < <( cat $RESP ))
done